name: glowblow
description: Some glowing animations.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_material_color_picker: ^1.0.5
  painter: ^0.4.0
  font_awesome_flutter:
  animator: ^1.0.0+5
  url_launcher: ^5.4.10
#  flat_icons_flutter: ^1.0.2
  outline_material_icons: ^0.1.1
  scoped_model: ^1.0.1
  screenshot: ^0.1.1
  image_gallery_saver: ^1.2.2
  image_picker: ^0.6.7+1
  share_extend: ^1.1.5
  flutter_screen_recording: ^1.0.6
  permission_handler: ^5.0.0+hotfix.8
#  snappable: ^1.0.1
#  open_file: ^3.0.1
#  full_screen_menu: ^0.1.2
#  image_cropper 1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: ama
      fonts:
        - asset: fonts/amatic.ttf
    - family: lob
      fonts:
        - asset: fonts/lobster.ttf
    #    - family: mon
    #      fonts:
    #        - asset: fonts/monoton.ttf
    #    - family: sai
    #      fonts:
    #        - asset: fonts/saira.ttf
    - family: pac
      fonts:
        - asset: fonts/pacifico.ttf
    #          weight: 300

    - family: ci
      fonts:
        - asset: fonts/custom_icons.ttf
  #    - family: autograph
  #      fonts:
  #        - asset: fonts/autograph.ttf
  #    - family: sign
  #      fonts:
  #        - asset: fonts/signerica.ttf
  #    - family: handwriting
  #      fonts:
  #        - asset: fonts/phont_handwriting.ttf
